# Generated by Django 4.2.4 on 2023-08-20 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_alive', models.BooleanField(max_length=1)),
                ('profile_image', models.FileField(null=True, upload_to=True)),
                ('gender', models.CharField(max_length=45)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('books', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.SmallIntegerField(default=2023)),
                ('page', models.PositiveSmallIntegerField(default=60)),
                ('is_there', models.BooleanField(max_length=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.author')),
            ],
        ),
        migrations.CreateModel(
            name='Manzil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(default=1)),
                ('shahar', models.CharField(max_length=45)),
                ('tuman', models.CharField(max_length=45)),
                ('qishloq', models.CharField(blank=True, max_length=45, null=True)),
                ('kocha', models.CharField(max_length=45)),
                ('uy', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile_image', models.FileField(null=True, upload_to=True)),
                ('age', models.PositiveSmallIntegerField(default=20)),
                ('phone', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(max_length=1)),
                ('gender', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='BookRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField()),
                ('to_time', models.SmallIntegerField(default=2)),
                ('book_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.book')),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.student')),
            ],
        ),
    ]
