# Generated by Django 4.2.4 on 2023-08-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_author_gender_alter_author_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(blank=True, max_length=1, null=True),
        ),
    ]
